sudo: required
services:
    - docker
    
before_install:
    - docker build -t rizwan/docker-react-complex-client -f ./client/Dockerfile.dev ./client 
#   - docker build -t rizwan/docker-react-complex-test2 -f ./client/Dockerfile.dev ./client 

script:
    - docker run rizwan/docker-react-complex-client npm run test -- --coverage
# can have multiple
    
after_success:
    - docker build -t radurrani/multi-client ./client
    - docker build -t radurrani/multi-nginx ./nginx
    - docker build -t radurrani/multi-server ./server
    - docker build -t radurrani/multi-worker ./worker

# log into docker
    - echo "$DOCKER_PASSWORD" : docker login -u "$DOCKER_ID" --pasword-stdin
# push images to docker hub

    - docker push radurrani/multi-client
    - docker push radurrani/multi-nginx 
    - docker push radurrani/multi-server
    - docker push radurrani/multi-worker
    